### ISSUE TITLE
0から始まる社員番号を入力すると例外が発生する。

### ISSUE THREAD

**Issue by shiftdownet** [soudai-aisw/aisw_bihin#43]
# 再現環境
Windows 10
コミットID：https://github.com/soudai-aisw/aisw_bihin/commit/c5cb42c8643deeb1f119fd541b7c7b357a2210c2

# 前提条件
現在状態が、StandbyUserIdInput

# 入力値
0079522

# 結果
```
社員証をかざしてください
>0079522
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    main()
  File "main.py", line 8, in main
    state_controller.run()
  File "C:\WorkingCopy\aisw_bihin\EquipmentBookingSystem\src\StateController.py", line 46, in run
    self.step()
  File "C:\WorkingCopy\aisw_bihin\EquipmentBookingSystem\src\StateController.py", line 24, in step
    self.__current.exit()
  File "C:\WorkingCopy\aisw_bihin\EquipmentBookingSystem\src\state\StandbyUserIdInput.py", line 25, in exit
    match_id = db.DBmatching_EmpIDtoEmpNo(employee_id)
  File "C:\WorkingCopy\aisw_bihin\EquipmentBookingSystem\src\db\matching\DBmatching.py", line 24, in DBmatching_EmpIDtoEmpNo
    df_Emp = df_csv.query('備考 == {}'.format(EmpID))
  File "C:\Users\roki\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\frame.py", line 4055, in query
    res = self.eval(expr, **kwargs)
  File "C:\Users\roki\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\frame.py", line 4186, in eval
    return _eval(expr, inplace=inplace, **kwargs)
  File "C:\Users\roki\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\computation\eval.py", line 348, in eval
    parsed_expr = Expr(expr, engine=engine, parser=parser, env=env)
  File "C:\Users\roki\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\computation\expr.py", line 806, in __init__
    self.terms = self.parse()
  File "C:\Users\roki\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\computation\expr.py", line 825, in parse
    return self._visitor.visit(self.expr)
  File "C:\Users\roki\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\computation\expr.py", line 407, in visit
    raise e
  File "C:\Users\roki\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\computation\expr.py", line 403, in visit
    node = ast.fix_missing_locations(ast.parse(clean))
  File "C:\Users\roki\AppData\Local\Programs\Python\Python37\lib\ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    備考 ==00 79522
                ^
SyntaxError: invalid syntax
```

# 対策案

キーボード入力できないようにする|
⇒デバッグが面倒に・・

# 類似

下記入力も同様にNGとなることを確認しました。

> 101.102.103.104
> aaa
> #5

**Comment by A-Yasue** [comment]
該当なければFalse返すはずだがいまいちエラー要因がわからない・・・。
とりあえず社員証認証時は、手打ち入力はじきたいな。
何か前に検討した気がするけど難しいんでしたっけ？

**Comment by shinichi-ozaki** [comment]
StandbyUserIdInputで入力されるデータはRFIDで読み取ったIDなので
社員番号ではなくてそのIDのパターン以外は弾かないといけないっすね。
(どんなデータかちょっと把握してないです。）
エラーですが、
https://github.com/soudai-aisw/aisw_bihin/blob/ebdaf94a3da9a64372de6d05a1390291c3283fcf/EquipmentBookingSystem/src/db/matching/DBmatching.py#L22
で入力が数字であれば問題ないんですが、文字列になると条件指定が上手くいかない？
>101.102.103.104
>aaa
>#5

こいつらは文字列と認識してるっぽいからエラーになると思うけど、

>0079522

こいつはわかんない。
00-00-00-00はOKだけど、00-00-00-はNG。
なんだろ。

**Comment by shiftdownet** [comment]
0から開始するシンタックスが許可されていないからですね。
10進数の記述ルールは正規表現で書くと、[1-9][0-9]*ですね。
C言語とかだと、接頭辞に0をつけると8進数扱いになったりしますが、
Pythonだと8進数の場合0o[0-9]+で表記しないといけないのでこれも該当せず。
ただ、例外的に、0+は何個ゼロがあってもゼロみたいです。。

じゃあなんで00-00-00-00がOKで、00-00-00-がダメなのかというと、
文法として完成していないからですね。
実はこの「-」、四則演算子として認識されています。
なのでもちろん
00*00+00-00/00
とかもOKです。
00-
はオペランドが足りていないのでNGですね。

queryメソッドは単に文字列を渡してマッチしているか見るメソッドではなく、
SQL文みたいに一定のルールに従って記述される必要があるようです。

文字列として扱いたいなら、クエリの変数が埋め込まれる部分を""で囲むのが手っ取り早いですが、
もちろんこれもユーザ入力に"が含まれると破壊されます
(XSSとかでよくある攻撃手法ですね)

一般的に、この手の攻撃に対応するためには、サニタイズ(以前もこの言葉出したな・・・)と言って、
攻撃コードが含まれる可能性があるユーザ入力を消毒する必要があります。

まぁ我々のアプリでそこまで意識する必要がないんですが、
他にもユーザが入力する文字列数を制限しない場合、バッファオーバーランを狙った攻撃手法(めちゃくちゃ長い文字列＋バッファオーバーラン以降のバイトに攻撃コードを仕込む)とかもありますね。

**Comment by shiftdownet** [comment]
ちなみに、攻撃コードが含まれる可能性があるデータを消毒すること(特殊文字をエスケープしたり置換したり)をサニタイズというのに対して、
ユーザ入力の妥当性を検証することをバリデーションって言いますね。

これら二つの目的は似て非なるので、バリデーションの結果、偶然に攻撃コードをシャットアウトできることはありますが、基本的には分けて考えるべきものです。

**Comment by shinichi-ozaki** [comment]
0から開始する数字でエラーが出るのはqueryメソッドの成約とかではなく、
そもそもPythonとしてエラーってことなんですね。思い込みアカン。

**Comment by soudai-aisw** [comment]
>サニタイズ(以前もこの言葉出したな・・・)
GM以上にSILS説明したときにみんな？でざわついたやつねw

**Comment by shiftdownet** [comment]
https://github.com/soudai-aisw/aisw_bihin/commit/0f38b7a1d9c036773a0776a9453779f003d64df1
